### ISSUE TITLE
Add option to override layout engine

### ISSUE THREAD

**Issue by forivall** [EFanZh/Graphviz-Preview#11]
in the cli, this is done with `-K`. This is also easily done with viz.js as mentioned in #10

**Comment by EFanZh** [comment]
Why not set the layout engine in the source code using the [`layout`](https://graphviz.gitlab.io/_pages/doc/info/attrs.html#d:layout) attribute?

**Comment by forivall** [comment]
Yeah, i discovered that attribute after I opened this issue. it was just a feature that I saw on viz.js's website, and I didn't know it was possible to control from the code. feel free to close.
