### ISSUE TITLE
worked once after install, now just displays "spawn EACCES"

### ISSUE THREAD

**Issue by warrenstephens** [EFanZh/Graphviz-Preview#12]
![image](https://user-images.githubusercontent.com/15000847/41358083-9afb3252-6ef5-11e8-8b74-0fd66de001a1.png)

**Comment by EFanZh** [comment]
Where do you put your “dot” program?

**Comment by warrenstephens** [comment]
I used "brew install graphviz".  It appears to have put everything into /usr/local/bin

**Comment by EFanZh** [comment]
Can you generate a graph manually in a command line? For example what is the output of this command?

```
echo 'graph{}' | dot -Tsvg
```

Also, what is your setting regarding to Graphviz Preview?

**Comment by warrenstephens** [comment]
![image](https://user-images.githubusercontent.com/15000847/41467205-89fca8c6-7073-11e8-8d27-a2833f0c8ff4.png)

and

![image](https://user-images.githubusercontent.com/15000847/41467262-cbeb5480-7073-11e8-9060-6ce215b5511a.png)

**Comment by EFanZh** [comment]
The `graphvizPreview.dotPath` should be set to the path of the executable, not the directory containing it. Or, if the dot executable is in your `PATH` environment variable, you can set it to `null`.

**Comment by ft1996** [comment]
我也出现了这个问题，config是：
```
dotPath": "/Users/day/Documents/GitHub/vueTest/vueTemplate/test.dot",
    "graphvizPreview.engine": "dot",
```

spawn eacces

**Comment by warrenstephens** [comment]
Hey thanks!  Changing to null fixed it.
