### ISSUE TITLE
Question: Export Options

### ISSUE THREAD

**Issue by whoiskevinrich** [EFanZh/Graphviz-Preview#14]
Is it possible for this to output to formats other than SVG?

**Comment by singularitti** [comment]
The same question here. Could it be at least in support of pdf? There are several tools that can do this like [svg2pdf.js](https://github.com/yWorks/svg2pdf.js/tree/master).

**Comment by EFanZh** [comment]
It is possible to output formats other than SVG. Let me see what I can do.

**Comment by EFanZh** [comment]
Fixed in 6c9ebd86eb322748978f6dac21f73a90848ca5c3.

**Comment by whoiskevinrich** [comment]
"Export" button still only allows export to SVG format. Is some setup involved?

**Comment by EFanZh** [comment]
@whoiskevinrich It is in the code repository, but not released yet.
