### ISSUE TITLE
Node with hyperlink 

### ISSUE THREAD

**Issue by jakeoung** [EFanZh/Graphviz-Preview#19]
I couldn't connect the hyperlink if I add on a node. Could you consider it?

**Comment by EFanZh** [comment]
There’s a bug in VS Code that prevents links in SVG from being opened. I have submitted a pull request (Microsoft/vscode#73272) for it.

**Comment by EFanZh** [comment]
The bug in VS Code that prevents hyperlinks being opened has is fixed in VS Code 1.35 and up. You should be able to open hyperlinks with Graphviz Preview of version 1.3.3.
