### ISSUE TITLE
Allow to choose layout engine

### ISSUE THREAD

**Issue by letmaik** [EFanZh/Graphviz-Preview#23]
I'm interested in `circo` for example.

**Comment by EFanZh** [comment]
You can add `layout = circo` to your source to specify the layout engine to use.

**Comment by letmaik** [comment]
Yes, that's one option, but it would still be good to switch between layouts dynamically. My use case is some auto-generated graph that I need to explore in some way. Having to go to the source file each time to try different layouts would be a minor annoyance. I could imagine a dropdown in the preview to select the engine.

**Comment by EFanZh** [comment]
I see. I think I can implement this feature in the future.

**Comment by EFanZh** [comment]
Maybe this is a bit too late, but you can now specify the layout engine to use by specifying `["-Glayout=<ENGINE>"]` for the `graphvizPreview.dotExtraArgs` configuration from 1.5.0 onwards. For example:

```json
{
    "graphvizPreview.dotExtraArgs": [
        "-Glayout=circo"
    ]
}
```
