### ISSUE TITLE
Program not found: "dot" Please check your configuration

### ISSUE THREAD

**Issue by megadime** [EFanZh/Graphviz-Preview#24]
I am totally  confused about the installation.
1. Does this extension need the "Graphviz (dot) language support for Visual Studio Code" by
stephanvs to be installed?

2. If yes I know I am supposed to enter in settings.json the path of the executable but where is it in windows? I have tried with no luck
"graphvizPreview.dotPath": "C:\\Users\\myUserName\\.vscode\\extensions\\stephanvs.dot-0.0.1"

thank you!

**Comment by EFanZh** [comment]
1. That extension is not needed for Graphviz Preview to work, but without it, you lose the ability to highlight the DOT syntax.
2. By default, Windows does not contain the dot executable, you’ll have to download it from the Internet:
   - https://www.graphviz.org/download/
   - https://chocolatey.org/packages/Graphviz
