### ISSUE TITLE
In visual code: it warns "Cannot read property 'on' of undefined"

### ISSUE THREAD

**Issue by Luzy1130** [EFanZh/Graphviz-Preview#26]
![image](https://user-images.githubusercontent.com/8627210/67378386-bff88180-f5b9-11e9-8377-4ea0d4b70862.png)

if some one can tell me what's wrong with it and how to solve? thanks

vsc version: 1.39.1

**Comment by EFanZh** [comment]
What is your operating system and `graphvizPreview.dotPath` configuration?

**Comment by Luzy1130** [comment]
> What is your operating system and `graphvizPreview.dotPath` configuration?

![image](https://user-images.githubusercontent.com/8627210/67388349-0e624c00-f5cb-11e9-8e00-c292d75e1dbe.png)
OS： mac catalina(10.15)

**Comment by EFanZh** [comment]
The `graphvizPreview.dotPath` configuration should be set to the path of the `dot` executable, not the directory containing it.

**Comment by Luzy1130** [comment]
> The `graphvizPreview.dotPath` configuration should be set to the path of the `dot` executable, not the directory containing it.

OK, the problem is solved, thanks.
