### ISSUE TITLE
Doesn't seem to be working.

### ISSUE THREAD

**Issue by snarlynarwhal** [EFanZh/Graphviz-Preview#3]
I keep getting this error: `Unable to open 'Preview 'mygraph.dot'': File not found: dot.`

**Comment by EFanZh** [comment]
@snarlynarwhal You should set the “graphviz-preview.dotPath” configuration to the path of the “dot” program.

**Comment by snarlynarwhal** [comment]
Forgive, my noobness, but I'm new to VSCode and using VSCode extensions. How do I set that configuration setting? I navigated to the extension page within VSCode and found the setting and command, but can't seem to edit it.

**Comment by EFanZh** [comment]
@snarlynarwhal There are two panels in the user setting page, the left panel contains the default settings which are read only; you should put your settings in the right panel. You can copy “dotPath” setting to the right panel using “Replace in settings”, and edit it in the right panel.

![image](https://user-images.githubusercontent.com/2160692/29735341-d5f334e6-8a2a-11e7-8539-a14779f0ee66.png)

**Comment by snarlynarwhal** [comment]
I didn't see the second paneI since I went to `view -> extensions` instead of `file -> preferences -> settings`. The former shows you the settings in a read only manner so it confused me!

Might want to mention `file -> preferences -> settings` in the readme for VSCode newbies like myself. Thank you very much for the help!

**Comment by EFanZh** [comment]
You are welcome. I’ve added some configuration instructions in the readme file.
