### ISSUE TITLE
How to enable the preview

### ISSUE THREAD

**Issue by longzy-oushu** [EFanZh/Graphviz-Preview#4]
Can't find window of graphviz preview.

In the shortcut settings not keyboard shortcut named graphviz.preview found.
Although I do found the dot path in the setting.
So I overrided the setting with the fowllowing:
    `"graphviz-preview.dotPath": "/usr/local/bin/dot"`
FYI i'm using mac and installed the graphviz using brew, i'm not sure what is going on and pls tell me how to fix this..

**Comment by EFanZh** [comment]
@ion2014 You can open the command palette, then select “Graphviz: Show Preview” command.
