### ISSUE TITLE
Graphviz preview, Unknown error occurred.

### ISSUE THREAD

**Issue by datauduong** [EFanZh/Graphviz-Preview#7]
I've tried F1/Ctrl+Shift+P, then I am selecting 
Graphviz show preview, I am getting an error:

Unable to open 'Preview 'test.gv": An unknown error occurred. Please consult the log for more details.

test.gv
digraph abc {
a -> b -> c -> a
}

[exthost1.log](https://github.com/EFanZh/Graphviz-Preview/files/1721573/exthost1.log)

**Comment by datauduong** [comment]
I have noted the setting mention in the discussion about the setting "graphviz-preview.dotPath", can you tell me what is the dot program or where to download program ?

**Comment by datauduong** [comment]
I have worked it out.
Here is the information needed in the Install of Graphviz-Preview.
1. Install from http://graphviz.org/download/
2. Open Visual Studio Code Setting, find graphviz-preview.dotPath and copy to user setting.
My setting is: 
"graphviz-preview.dotPath": "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe"

to use the Graphviz Preview.
1. Make your Graphviz code active windows in Visual Studio Code.
2. Press F1 or Ctrl + Shift + P, then select "Graphviz: Show Preview"

**Comment by EFanZh** [comment]
Thanks for reporting, I’m reopening this issue because I think under no circumstance should “unknown error” occur. This error message is very confusing to users. Until I can display an appropriate error message, I’m leaving this issue open.

**Comment by EFanZh** [comment]
Fixed in a6a5b6015115ad821cbdf3f6ab90212350d5be18.
