### ISSUE TITLE
e.replace is not a function

### ISSUE THREAD

**Issue by tz-reinberger** [EFanZh/Graphviz-Preview#79]
The extension used to work, but as I tried it today, I received the error from Code, as seen in the screenshot.
![2024-08-06 11_30_11-FancyWMInteractiveOverlay](https://github.com/user-attachments/assets/3ea645bd-d7de-46d4-a409-ebb285527f8a)
I'm not sure why it stopped working. Maybe VSCode's API changed?

Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by EFanZh** [comment]
@tz-reinberger: I will take a look at it. In the mean time, you could try to downgrade to an old version to see if it works: <https://marketplace.visualstudio.com/_apis/public/gallery/publishers/EFanZh/vsextensions/graphviz-preview/1.6.4/vspackage>. Also, do you have any custom settings of Graphviz Preview?

**Comment by tz-reinberger** [comment]
@EFanZh 
1.6.4 works without any problems.
I used VSCode's version downgrade feature to restore the old version, as the vsix file doesn't install, requiring me to "install it within Visual Studio Code".
I don't use any custom settings, no.

**Comment by EFanZh** [comment]
Hi @tz-reinberger, I have released a new version 1.7.2, could you verify whether it fixes your problem?

**Comment by tz-reinberger** [comment]
Yes, that fixes it. Thank you!

**Comment by EFanZh** [comment]
@tz-reinberger: Would you like to share your full configuration of your VS Code including the global configuration and the workspace one? I am still not sure what exactly has gone wrong.

**Comment by tz-reinberger** [comment]
@EFanZh 
I poked around the settings and found an invalid value for the terminal warning on multiline input, which I removed.
I tried reinstalling the previous version that gave issues, and that one seems fine now.
So maybe the wrong VSCode Settings messed something in the extension up?
I can't reproduce the issue any more, unfortunately.
