### ISSUE TITLE
Save image?

### ISSUE THREAD

**Issue by iamsergii** [EFanZh/Graphviz-Preview#9]
Is it possible to implement "Save" feature for the generated graph?

**Comment by EFanZh** [comment]
Yes, it is on the roadmap. I have been working on a new version of Graphviz Preview, exporting will be implemented in the future.

**Comment by iamsergii** [comment]
Great,thanks!

**Comment by jhvanderven** [comment]
+1
I solved it by installing the Save and Run extension. I added the following command: 
```
    "saveAndRun": {
        "commands": [
          {
            "match": ".gv",
            "cmd": "dot -Tpng -O ${file}",
            "useShortcut": false
          },
        ]
    }

```

It then automatically generates file.gv.png.

**Comment by EFanZh** [comment]
I have added an “Export” button to save the generated graph in the develop version. This function will be in the next release of Graphviz Preview.
